language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn test -- --coverage
  - yarn build
  - bash <(curl -s https://codecov.io/bash)
after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token yarn coveralls